artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rounaccc/Severity-of-Toxic-Comments-End-to-End/raw/main/ToxicCommentsData.zip
  local_data_file: artifacts/data_ingestion/ToxicCommentsData.zip
  unzip_dir: artifacts/data_ingestion