artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rounaccc/Severity-of-Toxic-Comments-End-to-End/raw/main/ToxicCommentsData.zip
  local_data_file: artifacts/data_ingestion/ToxicCommentsData.zip
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  test_data_path: artifacts/data_ingestion/test_data.csv
  train_data_path: artifacts/data_ingestion/train_data.csv
  tokenizer_path: artifacts/data_transformation/tokenizer

model_trainer:
  root_dir: artifacts/model_trainer
  processed_test_data_dir: artifacts/data_transformation/processed_test_data.csv
  processed_train_data_dir: artifacts/data_transformation/processed_train_data.csv
  tokenizer_dir: artifacts/data_transformation/tokenizer
